<?php

class EmailTemplateCatalog
{
    public static function getDefaultTemplates(): array
    {
        return [
            [
                'name' => 'Lancement produit',
                'category' => 'Annonce',
                'subject' => 'Notre nouveau produit est disponible',
                'content' => '<div style="font-family: Arial, sans-serif; max-width: 640px; margin: 0 auto; padding: 24px; background: #f5f8ff; border-radius: 20px;"><div style="background:#1d4ed8;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 16px;font-size:30px;">Notre nouveau produit est disponible</h1><p style="margin:0 0 18px;line-height:1.7;">Découvrez une solution plus simple, plus rapide et plus puissante pour votre quotidien.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#1d4ed8;border-radius:999px;text-decoration:none;font-weight:700;">Voir le produit</a></div><div style="padding:0 0 10px;"><p style="margin:0 0 8px;color:#334155;">Pourquoi l’essayer ?</p><ul style="margin:0 0 0 18px;color:#475569;line-height:1.7;"><li>Gain de temps</li><li>Résultat immédiat</li><li>Support dédié</li></ul></div></div>',
                'plain_text' => 'Notre nouveau produit est disponible\n\nDécouvrez une solution plus simple, plus rapide et plus puissante pour votre quotidien.\n\nVoir le produit: [URL]',
            ],
            [
                'name' => 'Offre spéciale',
                'category' => 'Promotion',
                'subject' => 'Profitez d’une offre limitée',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#fff9f2;border-radius:20px;"><div style="background:#ed8936;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Offre limitée</h1><p style="margin:0 0 18px;line-height:1.7;">Réductions exclusives et avantages réservés aux abonnés jusqu’à la fin de la semaine.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#ed8936;border-radius:999px;text-decoration:none;font-weight:700;">Profiter de l’offre</a></div><p style="margin:0;color:#4b5563;line-height:1.7;">Livraison gratuite, bonus exclusif et accès prioritaire.</p></div>',
                'plain_text' => 'Profitez d’une offre limitée\n\nRéductions exclusives et avantages réservés aux abonnés jusqu’à la fin de la semaine.\n\nProfiter de l’offre: [URL]',
            ],
            [
                'name' => 'Invitation AfiaZone',
                'category' => 'Invitation',
                'subject' => 'Votre expertise peut transformer la santé en Afrique',
                'content' => '<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f3f7f8;padding:24px;font-family:Arial,sans-serif;color:#0f172a;"><tr><td align="center"><table width="640" cellpadding="0" cellspacing="0" border="0" style="background:#ffffff;border-radius:16px;overflow:hidden;"><tr><td align="center"><img src="/public/assets/images/img-1.jpg" alt="AfiaZone - Connectons les acteurs de la santé" width="640" style="display:block;width:100%;max-width:640px;height:auto;border:0;"></td></tr><tr><td style="padding:36px 32px 24px;"><h1 style="margin:0 0 18px;color:#0b7a75;font-size:32px;line-height:1.1;">Votre expertise peut transformer la santé en Afrique.</h1><p style="margin:0 0 18px;font-size:16px;line-height:1.7;color:#334155;">Bonjour <strong>{{Nom}}</strong>,</p><p style="margin:0 0 18px;font-size:16px;line-height:1.7;color:#334155;">Nous avons le plaisir de vous inviter à rejoindre <strong>AfiaZone</strong>, la plateforme qui connecte les chercheurs, professionnels de santé, universités, hôpitaux, ONG et innovateurs africains.</p></td></tr><tr><td align="center" style="padding:0 32px 32px;"><img src="/public/assets/images/img-2.jpg" alt="Communauté scientifique" width="560" style="display:block;width:100%;max-width:560px;border-radius:8px;height:auto;border:0;"></td></tr><tr><td style="padding:0 32px 30px;"><h2 style="margin:0 0 14px;color:#0b7a75;font-size:24px;">Pourquoi rejoindre AfiaZone ?</h2><ul style="margin:0 0 0 18px;padding:0;color:#475569;line-height:1.75;font-size:16px;"><li>🩺 Publiez vos recherches scientifiques</li><li>🌍 Développez votre réseau professionnel</li><li>🤝 Trouvez des partenaires de recherche</li><li>📚 Partagez vos conférences et formations</li><li>💼 Valorisez votre expertise</li><li>🚀 Participez à la plus grande communauté santé africaine</li></ul></td></tr><tr><td align="center" style="padding:0 32px 32px;"><img src="/public/assets/images/img-3.jpg" alt="Plateforme AfiaZone" width="560" style="display:block;width:100%;max-width:560px;border-radius:8px;height:auto;border:0;"></td></tr><tr><td align="center" style="padding:0 0 36px;"><a href="https://afiazone.com" style="display:inline-block;background:#0b7a75;color:#ffffff;text-decoration:none;padding:14px 24px;border-radius:999px;font-weight:700;font-size:16px;">Créer gratuitement mon compte</a></td></tr><tr><td align="center" style="padding:0 32px 40px;"><img src="/public/assets/images/img-4.jpg" alt="Construisons la santé de demain" width="560" style="display:block;width:100%;max-width:560px;border-radius:8px;height:auto;border:0;"></td></tr><tr><td style="padding:0 32px 32px;color:#334155;font-size:16px;line-height:1.75;"><h2 style="margin:0 0 14px;color:#0b7a75;font-size:24px;">Construisons ensemble l’avenir de la santé.</h2><p style="margin:0 0 12px;">Les grandes innovations naissent de la collaboration. En rejoignant AfiaZone aujourd’hui, vous contribuez à bâtir une communauté scientifique africaine plus forte, plus visible et plus connectée.</p><p style="margin:0;color:#0b7a75;font-weight:700;">L’équipe AfiaZone<br><a href="https://afiazone.com" style="color:#0b7a75;text-decoration:none;">https://afiazone.com</a></p></td></tr></table></td></tr></table>',
                'plain_text' => 'Votre expertise peut transformer la santé en Afrique.\n\nBonjour {{Nom}},\n\nNous avons le plaisir de vous inviter à rejoindre AfiaZone, la plateforme qui connecte les chercheurs, professionnels de santé, universités, hôpitaux, ONG et innovateurs africains.\n\nPourquoi rejoindre AfiaZone ?\n- Publiez vos recherches scientifiques\n- Développez votre réseau professionnel\n- Trouvez des partenaires de recherche\n- Partagez vos conférences et formations\n- Valorisez votre expertise\n- Participez à la plus grande communauté santé africaine\n\nCréer gratuitement mon compte: https://afiazone.com\n\nConstruisons ensemble l’avenir de la santé.\n\nL’équipe AfiaZone\nhttps://afiazone.com',
            ],
            [
                'name' => 'Invitation événement',
                'category' => 'Événement',
                'subject' => 'Vous êtes invité à notre événement',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#ecfdf5;border-radius:20px;"><div style="background:#047857;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Événement en ligne</h1><p style="margin:0 0 18px;line-height:1.7;">Rejoignez-nous pour une session live avec conseils, cas concrets et réponses à vos questions.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#047857;border-radius:999px;text-decoration:none;font-weight:700;">Je m’inscris</a></div><p style="margin:0;color:#164e63;line-height:1.7;"><strong>Date :</strong> 20 juin<br><strong>Heure :</strong> 14h00</p></div>',
                'plain_text' => 'Vous êtes invité à notre événement\n\nRejoignez-nous pour une session live avec conseils, cas concrets et réponses à vos questions.\n\nJe m’inscris: [URL]',
            ],
            [
                'name' => 'Article de blog',
                'category' => 'Blog',
                'subject' => 'Découvrez notre dernier article',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f8fafc;border-radius:20px;"><h1 style="margin:0 0 18px;font-size:30px;color:#1d4ed8;">Découvrez notre dernier article</h1><div style="background:#fff;padding:20px;border-radius:18px;margin-bottom:16px;"><p style="margin:0;color:#475569;line-height:1.7;">Un contenu simple, concret et directement applicable pour améliorer vos résultats.</p><a href="#" style="display:inline-block;margin-top:12px;color:#1d4ed8;font-weight:700;text-decoration:none;">Lire l’article</a></div></div>',
                'plain_text' => 'Découvrez notre dernier article\n\nUn contenu simple, concret et directement applicable pour améliorer vos résultats.\n\nLire l’article: [URL]',
            ],
            [
                'name' => 'Témoignage client',
                'category' => 'Proof',
                'subject' => 'Ce que nos clients disent de nous',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#eef2ff;border-radius:20px;"><div style="background:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><p style="margin:0 0 14px;font-size:18px;color:#334155;line-height:1.7;">“Grâce à cette solution, notre conversion a augmenté de 35 % en deux mois.”</p><strong style="color:#1d4ed8;">— Client satisfait</strong></div><p style="margin:0;color:#475569;line-height:1.7;">Des résultats concrets, un accompagnement clair et des clients ravis.</p></div>',
                'plain_text' => 'Ce que nos clients disent de nous\n\n“Grâce à cette solution, notre conversion a augmenté de 35 % en deux mois.”\n\n— Client satisfait',
            ],
            [
                'name' => 'Bilan mensuel',
                'category' => 'Rapport',
                'subject' => 'Votre bilan du mois',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#eff6ff;border-radius:20px;"><h1 style="margin:0 0 18px;font-size:30px;color:#1d4ed8;">Votre bilan du mois</h1><div style="background:#fff;padding:20px;border-radius:18px;margin-bottom:16px;"><h2 style="margin:0 0 10px;font-size:22px;color:#0f172a;">Ce qui a fonctionné</h2><p style="margin:0;color:#475569;line-height:1.7;">Vos campagnes ont généré une meilleure rétention et davantage de conversions.</p></div><div style="background:#fff;padding:20px;border-radius:18px;"><h2 style="margin:0 0 10px;font-size:22px;color:#0f172a;">À venir</h2><p style="margin:0;color:#475569;line-height:1.7;">Nouveaux formats, nouveaux messages et plus d’optimisation.</p></div></div>',
                'plain_text' => 'Votre bilan du mois\n\nCe qui a fonctionné : vos campagnes ont généré une meilleure rétention et davantage de conversions.\n\nÀ venir : nouveaux formats, nouveaux messages et plus d’optimisation.',
            ],
            [
                'name' => 'Newsletter générale',
                'category' => 'Newsletter',
                'subject' => 'Les nouvelles du moment',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f8fafc;border-radius:20px;"><h1 style="margin:0 0 18px;font-size:30px;color:#0f172a;">Les nouvelles du moment</h1><div style="background:#fff;padding:20px;border-radius:18px;margin-bottom:16px;"><h2 style="margin:0 0 10px;font-size:22px;color:#1d4ed8;">Ce qui s’est passé</h2><p style="margin:0;color:#475569;line-height:1.7;">Retrouvez les annonces clés de la semaine dans ce numéro.</p></div><div style="background:#fff;padding:20px;border-radius:18px;"><h2 style="margin:0 0 10px;font-size:22px;color:#1d4ed8;">À venir</h2><p style="margin:0;color:#475569;line-height:1.7;">Des nouveautés, des événements et des offres à ne pas manquer.</p></div></div>',
                'plain_text' => 'Les nouvelles du moment\n\nCe qui s’est passé : retrouvez les annonces clés de la semaine dans ce numéro.\n\nÀ venir : des nouveautés, des événements et des offres à ne pas manquer.',
            ],
            [
                'name' => 'Relance panier',
                'category' => 'Relance',
                'subject' => 'Votre panier vous attend',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#fffbeb;border-radius:20px;"><div style="background:#b45309;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Votre panier vous attend</h1><p style="margin:0 0 18px;line-height:1.7;">Finalisez votre commande avant la fin de l’offre de lancement.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#b45309;border-radius:999px;text-decoration:none;font-weight:700;">Finaliser ma commande</a></div><p style="margin:0;color:#4b5563;line-height:1.7;">Offre limitée, livraison rapide et remises exclusives.</p></div>',
                'plain_text' => 'Votre panier vous attend\n\nFinalisez votre commande avant la fin de l’offre de lancement.\n\nFinaliser ma commande: [URL]',
            ],
            [
                'name' => 'Présentation service',
                'category' => 'Service',
                'subject' => 'Découvrez notre nouveau service',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f0fdf4;border-radius:20px;"><div style="background:#15803d;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Un nouveau service pour vous</h1><p style="margin:0 0 18px;line-height:1.7;">Un accompagnement simple pour gagner du temps et obtenir de meilleurs résultats.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#15803d;border-radius:999px;text-decoration:none;font-weight:700;">Découvrir le service</a></div><p style="margin:0;color:#334155;line-height:1.7;">Support personnalisé, outils pratiques et suivi efficace.</p></div>',
                'plain_text' => 'Découvrez notre nouveau service\n\nUn accompagnement simple pour gagner du temps et obtenir de meilleurs résultats.\n\nDécouvrir le service: [URL]',
            ],
            [
                'name' => 'Annonce fonctionnalité',
                'category' => 'Produit',
                'subject' => 'Nouvelle fonctionnalité disponible',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#eff6ff;border-radius:20px;"><div style="background:#2563eb;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Nouvelle fonctionnalité</h1><p style="margin:0 0 18px;line-height:1.7;">Une nouveauté pensée pour simplifier votre workflow et améliorer votre efficacité.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#2563eb;border-radius:999px;text-decoration:none;font-weight:700;">Tester la fonctionnalité</a></div><p style="margin:0;color:#334155;line-height:1.7;">Intuitive, rapide et immédiatement utile dans votre quotidien.</p></div>',
                'plain_text' => 'Nouvelle fonctionnalité disponible\n\nUne nouveauté pensée pour simplifier votre workflow et améliorer votre efficacité.\n\nTester la fonctionnalité: [URL]',
            ],
            [
                'name' => 'Mise à jour service',
                'category' => 'Produit',
                'subject' => 'Mise à jour importante pour votre service',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#fffdf7;border-radius:20px;"><div style="background:#d97706;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Mise à jour majeure</h1><p style="margin:0 0 18px;line-height:1.7;">Découvrez les nouvelles améliorations qui vont vous faire gagner du temps.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#d97706;border-radius:999px;text-decoration:none;font-weight:700;">Voir les détails</a></div></div>',
                'plain_text' => 'Mise à jour importante pour votre service\n\nDécouvrez les nouvelles améliorations qui vont vous faire gagner du temps.\n\nVoir les détails: [URL]',
            ],
            [
                'name' => 'Guide pratique',
                'category' => 'Éducation',
                'subject' => 'Guide pratique pour réussir',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f0f9ff;border-radius:20px;"><h1 style="margin:0 0 16px;font-size:30px;color:#0369a1;">Guide pratique</h1><div style="background:#fff;padding:20px;border-radius:18px;"><p style="margin:0;color:#475569;line-height:1.7;">Suivez nos étapes simples pour mieux organiser votre journée et atteindre vos objectifs.</p></div></div>',
                'plain_text' => 'Guide pratique pour réussir\n\nSuivez nos étapes simples pour mieux organiser votre journée et atteindre vos objectifs.\n\nLire le guide: [URL]',
            ],
            [
                'name' => 'Webinaire à venir',
                'category' => 'Événement',
                'subject' => 'Inscrivez-vous à notre webinaire',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#eff6ff;border-radius:20px;"><div style="background:#0284c7;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Webinaire gratuit</h1><p style="margin:0 0 18px;line-height:1.7;">Apprenez les meilleures pratiques en direct avec nos experts.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#0284c7;border-radius:999px;text-decoration:none;font-weight:700;">Je m’inscris</a></div></div>',
                'plain_text' => 'Inscrivez-vous à notre webinaire\n\nApprenez les meilleures pratiques en direct avec nos experts.\n\nJe m’inscris: [URL]',
            ],
            [
                'name' => 'Astuce du mois',
                'category' => 'Conseil',
                'subject' => 'L’astuce du mois pour gagner en efficacité',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#eef2ff;border-radius:20px;"><h1 style="margin:0 0 16px;font-size:30px;color:#1d4ed8;">Astuce du mois</h1><div style="background:#fff;padding:20px;border-radius:18px;"><p style="margin:0;color:#475569;line-height:1.7;">Une méthode simple pour mieux prioriser vos tâches et éviter les interruptions.</p></div></div>',
                'plain_text' => 'L’astuce du mois pour gagner en efficacité\n\nUne méthode simple pour mieux prioriser vos tâches et éviter les interruptions.\n\nEn savoir plus: [URL]',
            ],
            [
                'name' => 'Offre rentrée',
                'category' => 'Promotion',
                'subject' => 'Offre spéciale rentrée',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#fff7ed;border-radius:20px;"><div style="background:#c2410c;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Offre rentrée</h1><p style="margin:0 0 18px;line-height:1.7;">Préparez la rentrée avec une remise spéciale sur nos meilleures options.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#c2410c;border-radius:999px;text-decoration:none;font-weight:700;">En profiter</a></div></div>',
                'plain_text' => 'Offre spéciale rentrée\n\nPréparez la rentrée avec une remise spéciale sur nos meilleures options.\n\nEn profiter: [URL]',
            ],
            [
                'name' => 'Annonce de recrutement',
                'category' => 'RH',
                'subject' => 'Nous recrutons !',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f4f4ff;border-radius:20px;"><div style="background:#4338ca;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Rejoignez notre équipe</h1><p style="margin:0 0 18px;line-height:1.7;">Nous recherchons des talents motivés prêts à faire la différence.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#4338ca;border-radius:999px;text-decoration:none;font-weight:700;">Voir les postes</a></div></div>',
                'plain_text' => 'Nous recrutons !\n\nNous recherchons des talents motivés prêts à faire la différence.\n\nVoir les postes: [URL]',
            ],
            [
                'name' => 'Sondage client',
                'category' => 'Feedback',
                'subject' => 'Donnez-nous votre avis',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f8fafc;border-radius:20px;"><div style="background:#0f766e;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Votre avis compte</h1><p style="margin:0 0 18px;line-height:1.7;">Aidez-nous à améliorer nos services en répondant à ce court sondage.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#0f766e;border-radius:999px;text-decoration:none;font-weight:700;">Répondre</a></div></div>',
                'plain_text' => 'Donnez-nous votre avis\n\nAidez-nous à améliorer nos services en répondant à ce court sondage.\n\nRépondre: [URL]',
            ],
            [
                'name' => 'Invitation VIP',
                'category' => 'VIP',
                'subject' => 'Invitation exclusive pour nos meilleurs clients',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#fdf2f8;border-radius:20px;"><div style="background:#be185d;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Invitation VIP</h1><p style="margin:0 0 18px;line-height:1.7;">Accédez à un événement privé et des offres sur mesure.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#be185d;border-radius:999px;text-decoration:none;font-weight:700;">Réserver ma place</a></div></div>',
                'plain_text' => 'Invitation exclusive pour nos meilleurs clients\n\nAccédez à un événement privé et des offres sur mesure.\n\nRéserver ma place: [URL]',
            ],
            [
                'name' => 'Nouveautés mensuelles',
                'category' => 'Newsletter',
                'subject' => 'Ce qui change ce mois-ci',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#eef2ff;border-radius:20px;"><h1 style="margin:0 0 18px;font-size:30px;color:#1d4ed8;">Les nouveautés du mois</h1><div style="background:#fff;padding:20px;border-radius:18px;"><p style="margin:0;color:#475569;line-height:1.7;">Découvrez les dernières actualités, offres et conseils pour bien commencer.</p></div></div>',
                'plain_text' => 'Ce qui change ce mois-ci\n\nDécouvrez les dernières actualités, offres et conseils pour bien commencer.\n\nEn savoir plus: [URL]',
            ],
            [
                'name' => 'Meilleur du blog',
                'category' => 'Blog',
                'subject' => 'Le meilleur du blog cette semaine',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f8fafc;border-radius:20px;"><h1 style="margin:0 0 18px;font-size:30px;color:#0f172a;">Le meilleur du blog</h1><div style="background:#fff;padding:20px;border-radius:18px;"><p style="margin:0;color:#475569;line-height:1.7;">Une sélection des articles les plus utiles pour votre activité.</p></div></div>',
                'plain_text' => 'Le meilleur du blog cette semaine\n\nUne sélection des articles les plus utiles pour votre activité.\n\nLire maintenant: [URL]',
            ],
            [
                'name' => 'Présentation d’équipe',
                'category' => 'Entreprise',
                'subject' => 'Rencontrez notre équipe',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f7f7ff;border-radius:20px;"><div style="background:#4338ca;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Rencontrez l’équipe</h1><p style="margin:0 0 18px;line-height:1.7;">Découvrez les talents qui rendent votre expérience possible.</p></div></div>',
                'plain_text' => 'Rencontrez notre équipe\n\nDécouvrez les talents qui rendent votre expérience possible.\n\nEn savoir plus: [URL]',
            ],
            [
                'name' => 'Études de cas',
                'category' => 'Proof',
                'subject' => 'Cas concrets : ce qui a fonctionné',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#eef2ff;border-radius:20px;"><div style="background:#1e3a8a;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Étude de cas</h1><p style="margin:0 0 18px;line-height:1.7;">Découvrez un succès client et les résultats obtenus.</p></div></div>',
                'plain_text' => 'Cas concrets : ce qui a fonctionné\n\nDécouvrez un succès client et les résultats obtenus.\n\nLire l’étude de cas: [URL]',
            ],
            [
                'name' => 'FAQ clé',
                'category' => 'Support',
                'subject' => 'Questions fréquentes et réponses',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f8fafc;border-radius:20px;"><h1 style="margin:0 0 18px;font-size:30px;color:#0f172a;">FAQ clé</h1><div style="background:#fff;padding:20px;border-radius:18px;"><p style="margin:0;color:#475569;line-height:1.7;">Les réponses aux questions les plus fréquentes sur notre service.</p></div></div>',
                'plain_text' => 'Questions fréquentes et réponses\n\nLes réponses aux questions les plus fréquentes sur notre service.\n\nConsulter la FAQ: [URL]',
            ],
            [
                'name' => 'Rappel épisode',
                'category' => 'Podcast',
                'subject' => 'Ne manquez pas notre dernier épisode',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f0fdf4;border-radius:20px;"><h1 style="margin:0 0 18px;font-size:30px;color:#166534;">Nouveau podcast</h1><div style="background:#fff;padding:20px;border-radius:18px;"><p style="margin:0;color:#475569;line-height:1.7;">Découvrez les retours d’expérience de nos experts.</p></div></div>',
                'plain_text' => 'Ne manquez pas notre dernier épisode\n\nDécouvrez les retours d’expérience de nos experts.\n\nÉcouter maintenant: [URL]',
            ],
            [
                'name' => 'Checklist action',
                'category' => 'Conseil',
                'subject' => 'Checklist pour agir rapidement',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#fff7ed;border-radius:20px;"><h1 style="margin:0 0 18px;font-size:30px;color:#c2410c;">Checklist action</h1><div style="background:#fff;padding:20px;border-radius:18px;"><p style="margin:0;color:#475569;line-height:1.7;">3 actions simples pour améliorer vos résultats dès aujourd’hui.</p></div></div>',
                'plain_text' => 'Checklist pour agir rapidement\n\n3 actions simples pour améliorer vos résultats dès aujourd’hui.\n\nTéléchargez la checklist: [URL]',
            ],
            [
                'name' => 'Cadeau spécial',
                'category' => 'Promotion',
                'subject' => 'Cadeau offert avec votre prochaine commande',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#fdf2f8;border-radius:20px;"><div style="background:#be185d;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Cadeau spécial</h1><p style="margin:0 0 18px;line-height:1.7;">Recevez un cadeau exclusif pour toute commande passée cette semaine.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#be185d;border-radius:999px;text-decoration:none;font-weight:700;">Voir l’offre</a></div></div>',
                'plain_text' => 'Cadeau offert avec votre prochaine commande\n\nRecevez un cadeau exclusif pour toute commande passée cette semaine.\n\nVoir l’offre: [URL]',
            ],
            [
                'name' => 'Annonce partenariat',
                'category' => 'Partenariat',
                'subject' => 'Nouveau partenariat stratégique',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#eef2ff;border-radius:20px;"><div style="background:#1d4ed8;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Partenariat stratégique</h1><p style="margin:0 0 18px;line-height:1.7;">Nous unissons nos forces pour vous proposer plus de valeur.</p></div></div>',
                'plain_text' => 'Nouveau partenariat stratégique\n\nNous unissons nos forces pour vous proposer plus de valeur.\n\nEn savoir plus: [URL]',
            ],
            [
                'name' => 'Récompense fidélité',
                'category' => 'VIP',
                'subject' => 'Merci pour votre fidélité',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#ecfdf5;border-radius:20px;"><div style="background:#047857;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Merci pour votre fidélité</h1><p style="margin:0 0 18px;line-height:1.7;">Profitez d’une petite attention réservée à nos clients les plus fidèles.</p></div></div>',
                'plain_text' => 'Merci pour votre fidélité\n\nProfitez d’une petite attention réservée à nos clients les plus fidèles.\n\nRecevoir mon cadeau: [URL]',
            ],
            [
                'name' => 'Retour d’expérience',
                'category' => 'Témoignage',
                'subject' => 'Retour d’expérience client récent',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f7f7ff;border-radius:20px;"><div style="background:#4338ca;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Retour d’expérience</h1><p style="margin:0 0 18px;line-height:1.7;">Découvrez comment un client a atteint ses objectifs grâce à notre accompagnement.</p></div></div>',
                'plain_text' => 'Retour d’expérience client récent\n\nDécouvrez comment un client a atteint ses objectifs grâce à notre accompagnement.\n\nLire le témoignage: [URL]',
            ],
            [
                'name' => 'Calendrier des événements',
                'category' => 'Événement',
                'subject' => 'Toutes les dates à venir',
                'content' => '<div style="font-family: Arial, sans-serif; max-width:640px;margin:0 auto;padding:24px;background:#f0f9ff;border-radius:20px;"><div style="background:#0284c7;color:#fff;padding:24px;border-radius:18px;margin-bottom:20px;"><h1 style="margin:0 0 14px;font-size:30px;">Calendrier des événements</h1><p style="margin:0 0 18px;line-height:1.7;">Retrouvez toutes nos dates clés et inscrivez-vous aux sessions qui vous intéressent.</p><a href="#" style="display:inline-block;padding:12px 18px;background:#fff;color:#0284c7;border-radius:999px;text-decoration:none;font-weight:700;">Voir le calendrier</a></div></div>',
                'plain_text' => 'Toutes les dates à venir\n\nRetrouvez toutes nos dates clés et inscrivez-vous aux sessions qui vous intéressent.\n\nVoir le calendrier: [URL]',
            ],
        ];
    }
}
